### ISSUE TITLE
怎么验证vpn正常工作？

### ISSUE THREAD

**Issue by scgy5555** [doomdagger/L2TP-on-CentOS6#1]
实际上我是通过一键包安装的PPTP和L2TP/IPSec
又手动修改了所有配置
vps是Vultr购买的日本线路centos 6
所有服务都正常启动了，甚至把防火墙都关了
就是连接不上，提示服务器没有响应

是不是有某种方法可以验证某个设置没跑通？
还是vultr环境需要额外的设置?

**Comment by doomdagger** [comment]
只要是IaaS，任何环境都不需要额外的设置，一般有两种问题，（1）连不上VPN，（2）连上了，但是没有网络连接。第一种情况是L2TP本身的问题，第二种情况一般是iptables的问题。

验证第一种问题很简单，`ipsec verify`就可以。
第二种按照我写的那个文档里的设置来设置iptables，一般都没有问题，我已经按照这种设置装了5-6台机器了。

建议你不要用一键安装，reset一下服务器，从头按照这个文档来一遍，应该是没问题的。
:smile:

**Comment by scgy5555** [comment]
非常感谢，我完全找不到问题的原因。虽然是现象是1但是ipsec verify完全正常。
于是我重装了所有东西，重新设置过，然后可用了。

虽然可用了，不过连接的成功率依然很低，也容易掉线，同服务器下的ss就稳定的要死
是不是还有什么额外的操作？

**Comment by doomdagger** [comment]
对的，我确实也有连接总是失败的问题，掉线倒是不经常。我之前仔细查看过日志，并没有什么有用的信息。不过解决办法倒是有，我就是这么干的，效果还不错。

``` bash
service ipsec restart
service xl2tpd restart
service iptables restart
```

把这三个命令写到一个sh文件里，然后让`crontab`一天定期执行2-3次，重新启动这些服务可以提高L2TP的稳定性。
